### ISSUE TITLE
add relation shortcut to notes with single card

### ISSUE THREAD

**Issue by galantra** [Arthur-Milchior/anki-relation#5] opened 2019-08-10 10:55 UTC
This would be especially useful with Image Occlusion notes because each occlusion is always created as one separate note. So, relation tags are an easy way to bury occlusion "siblings" that were created from the same image.

The process would be a bit easier if you could add tags to notes with a single card. Although it will not immediately be applied to all similar notes, editing the IO note will transfer the tag to all notes that were created from the same image in the same dialog.

Alternative would be to do it manually. This would include looking up the ID after creation and pasting it.

**Comment by Arthur-Milchior** [comment] 2019-08-12 11:43
This is a duplicate of #4

**Closed as completed by Arthur-Milchior** 2019-08-12 11:43 UTC
Labels: duplicate
